# Generated by Django 4.1.7 on 2023-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_category_teacher_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
