# Generated by Django 4.1.7 on 2023-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('duration', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
