# Generated by Django 4.1.7 on 2023-02-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия Имя Отчество')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category', verbose_name='Должность')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category', verbose_name='Должность'),
        ),
    ]
